apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: taskapp
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/ts-a-devops/taskapp-backend:5d6b8fc
          command: ["alembic", "upgrade", "head"]

          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: FLASK_ENV
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: taskapp-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskapp-secrets
                  key: DATABASE_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
