apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: taskapp
  labels:
    app: taskapp-backend
spec:
  selector:
    app: taskapp-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
